title: 春菇菌的主页 The Blog of Yanchong Li 
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: dark # Or use dark

# Profile information
name: 李衍春菇菌！ (Yanchong Li)
tagline: Want to be a good Geophysicist! 
about-description: "I was graduated from Wuhan University, China, as a BS of geophysics and am now striving for a PhD degree in University of Illinois at Urbana-Champaign.\
I am very interested in geoscience problems, especially for large scale geodynamic, earthquakes and seismological problems. I am also in great fond of playing music, running, programming and great food! And COFFEE!!! Ahhhh\
This page is built for the purposes of spreading my knowledge (little but helps if I speak out, haha) and learning more systematically. \
 -♪(^∇^*)- \
Let's see how far this blog can go anyway."
 # Add Discription
pic: 79.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: Yanchong_Li@hotmail.com # Add your Email address
phone: None # Add your Phone number
website: lyc11776611.github.io # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: lyc11776611 # Add your Github handle
twitter: 'None' # Add your Twitter handle

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
